config/routes.rb
Rails.application.routes.draw do  
  namespace :api do 
    namespace :v1 do
      post 'authenticate', to: 'authentication#create'
      resources :users, only: [:index, :show, :create, :destroy] do
        resources :posts, only: [:index] do 
          resources :comments, only: [:index,:create]
        end
      end

      resources :posts, only: [] do
        resources :comments, only: [:create]
      end
    end
  end

  devise_for :users
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "users#show" 
  # Defines the root path route ("/")
  # root "articles#index"
  
  scope '/admin' do
  resources :users, only: [:index, :show,:new,:create,:update] do resources :posts, only: [:index, :show] 
  end
end
  resources :posts
  resources :comments, only: [:new, :create, :destroy]
  resources :likes, only: [:create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { maximum: 50 }
  validates :post_counter, presence: true, numericality: { only_integer: true }
  before_save :assign_role
  # has_secure_password
  has_many :comments, dependent: :destroy
  has_many :posts, foreign_key: 'user_id', dependent: :destroy
  has_many :likes, foreign_key: 'user_id', dependent: :destroy
  def recent_comments
    comments.last(3)
  end

  def admin?
    role == 'admin'
  end

  def assign_role
    self.role = 'user' if role.nil?
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class Api::V1::UsersController < AuthenticationController
      def index
        @users = User.all
        render json: @users
      end

      def show
        @user = User.find(params[:id])
        render json: @user
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.valid?
      @user.save
      redirect_to users_path
    else
      redirect_to new_users_path
    end
  end

  def edit
    @user = current_user
  end

  def update
    respond_to? do |format|
      if current_user.update(user_params)
        format.html { redirect_to user_path(current_user), notice: 'User was successfully updated.' }
      else
        render :edit, status: :unprocessable_entity
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :surname, :email, :password, :password_confirmation)
  end
end

app/views/users/_form.html.erb
<div>fkkkkkkkk</div>
<% input_classes = 'rounded' %>
<%= form_with( model: @user, local:true) do |form| %>
  <div>
   <%= form.label :name %><br>
    <%= form.text_field :name, placeholder: 'Name', class: input_classes %>
  </div>
  <div>
   <%= form.label :surname %><br>
    <%= form.text_area :surname, placeholder: 'surname', class: input_classes %>
  </div>
   <%= form.label :email %><br>
    <%= form.text_area :email, placeholder: 'email', class: input_classes %>
  </div>

   <div class="field">
    <%= form.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= form.password_field :password, autocomplete: "new-password" %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br />
    <%= form.password_field :password_confirmation, autocomplete: "new-password" %>
  </div>
  <div>
    <button type="submit" class="submit">
      add person
    </button>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="users-cont">
  <%= link_to "/users/#{user.id}" do %>
  <div class='user-cont'>
        <div class="img-cont">
           <img class="image" src="<%= user.photo %>" alt="Profile picture">
        </div>

        <div class="info-cont">
           <div class="name-cont"><%= user.name %></div>
           <div class="post-cont"> Number of posts: <%= user.post_counter%></div>
        </div>
        </div>
  <% end %>
  </div>

app/views/users/edit.html.erb
<%=render 'form'%>

app/views/users/index.html.erb
<div class='t'>
<%= render @users%>

</div>

app/views/users/new.html.erb
<%=render 'form'%>

app/views/users/show.html.erb
<%= render @user %>

<div class="bio-cont">
<h2>Bio</h2>
<p class="bio"><%=@user.bio%></p>
</div>
<%= render @user.posts%>
 <button class="button"><%=link_to 'see all posts' ,user_posts_path(@user)%></button>
 <button class="button"><%=link_to 'Add new post' ,new_post_path %></button>