config/routes.rb
Rails.application.routes.draw do  
  namespace :api do 
    namespace :v1 do
      post 'authenticate', to: 'authentication#create'
      resources :users, only: [:index, :show, :create, :destroy] do
        resources :posts, only: [:index] do 
          resources :comments, only: [:index,:create]
        end
      end

      resources :posts, only: [] do
        resources :comments, only: [:create]
      end
    end
  end

  devise_for :users
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "users#show" 
  # Defines the root path route ("/")
  # root "articles#index"
  
  scope '/admin' do
  resources :users, only: [:index, :show,:new,:create,:update] do resources :posts, only: [:index, :show] 
  end
end
  resources :posts
  resources :comments, only: [:new, :create, :destroy]
  resources :likes, only: [:create]
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }

  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :user, foreign_key: 'user_id'
  def update_post_count(count)
    user.update_attribute 'posts_counter', count
  end

  def recent_comments
    comments.last(5)
  end
end

app/controllers/api/v1/post_controller.rb
module Api
    module V1
      class  Api::V1::PostsController < AuthenticationController
        before_action :fetch_user, only: [:index,:show]
        before_action  :authenticate_request
        def index
          @posts = @user ? @user.posts.includes(:comments,:user) : Post.includes(:comments,:user) #n+1 fix
          render json: @posts
        end

        private
        def fetch_user
            @user = User.find(params[:user_id])
            end
      end
    end
  end

app/controllers/api/v1/posts_controller.rb
module Api
  module V1
    class Api::V1::PostsController < AuthenticationController
      before_action :fetch_user, only: %i[index show]
      before_action :authorize_request
      def index
        @posts = @user ? @user.posts.includes(:comments, :user) : Post.includes(:comments, :user) # n+1 fix
        render json: @posts
      end

      private

      def fetch_user
        @user = User.find(params[:user_id])
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  def index
    @user = current_user
  end

  def show
    @post = Post.includes(:comments, :user).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new post_params

    @post.user = current_user

    if @post.valid?
      @post.save
      redirect_to user_posts_path(current_user)
    else
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to user_post_path(current_user, @post)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% input_classes = 'rounded' %>
<%= form_with model: post, class: 'flex' do |form| %>
  <div>
    <%= form.text_field :title, placeholder: 'Title', class: input_classes %>
  </div>
  <div>
    <%= form.text_area :text, placeholder: 'Post description...', class: input_classes %>
  </div>
  <div>
    <button type="submit" class="submit">
      Add Post
    </button>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div>
<%=link_to user_post_path(@user,post)  do %>
<div class ="posts-cont">
    <h2><%=post.title %></h2>
    <p><%=post.text[0..14]...%></p>
   <div class="comment-likes">comments: <%=post.comments.size %> likes: <%=post.likes_counter%></div>
</div>
</div>
<% end %>
<div class="comments">
  <%post.recent_comments.each do |comment|%>
   <div>
   <%=comment.user.name%>: <%=comment.text%>
   </div> 
    <%end%>
 </div>

app/views/posts/edit.html.erb
<%= render "form", post:@post %>

app/views/posts/index.html.erb
<div>
<%=render @user %>
<%=render @user.posts%>
<div>

app/views/posts/new.html.erb
<div class="flex flex-col">
  <div class="text-xl mb-2">Create new post</div>
<%= render "form", post:@post %>
</div>

app/views/posts/show.html.erb
<div class="full-post-cont">
  <div class='full-post-cont-head'>
   <div><%= @post.title%> by <%= @post.user.name%></div>
   <div class='comment-likes'> comments: <%=@post.comments.size %> likes: <%=@post.likes_counter%></div>
  </div>
  <p><%= @post.text%></p>
  <div class="likes">
          <%= render partial: 'likes/form', locals: { post_id: @post.id } %>
        </div>
</div>
<div class="comments">
  <%@post.comments.each do |comment|%>
   <div>
   <%=comment.user.name%>: <%=comment.text%>
   <%=button_to "del",comment_path(comment), method: :delete  %>
   </div> 
    <%end%>
     <div>
    <%= render partial: 'comments/form', locals: { post: @post }  %>
  </div>
  <ul>
  <% if @current_user&.admin?%>
  <li><%= link_to "Edit Post", edit_post_path(@post) %></li>
  <li><%= button_to "del", post_path(@post), method: :delete  %></li>
  <%end%>
</ul>
 </div>